### ISSUE TITLE
Incorrect number of bins calculated for some workspaces

### ISSUE THREAD

**Issue by MatthewBowles** [mantidproject/mslice#360]
Some non-PSD workspaces (.e.g. [this one](https://github.com/mantidproject/mslice/files/2249440/MAR18120_Ei39.53meV.nxspe.zip)) are treated as having the wrong number of bins.

The Energy axis is saved in workspace.limits when the workspace is loaded as `-70, 40, 0.20992` (min, max, step size). Later, these values are used to calculate the number of steps:
```
 (40 - - 70) / 0.20092 = 524.009
```
Which is then rounded up to 525. For most workspaces, this is correct behaviour, but in this case the number of bins is 524. This can cause errors e.g. when changing the intensity, as the number of bins in the workspace is different to what is expected.

**Comment by srikanthravipati** [comment]
@SilkeSchomann I am not sure if this is still an issue. For the attached non-PSD workspace, calculated number of bins is 524 in Workbench!

**Comment by mducle** [comment]
@srikanthravipati and @SilkeSchomann 

Sorry the bug report is very sparse - it made sense at the time but that we a long while ago. I think this bug still exists, but it's not where you think it is.

The issue is in the `ceil` here: https://github.com/mantidproject/mslice/blob/0abeace37a91cdd82621f97bf8f6311f936acbcb/mslice/models/alg_workspace_ops.py#L5

This is really only called by the PSD-algorithms (because we use `BinMD` in thoses cases which explicitly requires the number of steps instead of the step sizes; for non-PSD workspaces we call `SofQWNormalisePolygons` which requires step sizes and not number of steps... ¯\_(ツ)_/¯

Also, it's called by the "intensity types" slice menu options which is where this bug comes in. If you load that data, then plot a slice with the default parameters and then click `Intensity` in the menu bar and `Chi''(Q,E)` and put in a number in the edit box (say `300`), then click ok, you get an error and the traceback:

```
Traceback (most recent call last):
  File "/home/mdl27/src/mslice/mslice/plotting/plot_window/slice_plot.py", line 313, in show_intensity_plot
    if not self._run_temp_dependent(slice_plotter_method, previous):
  File "/home/mdl27/src/mslice/mslice/plotting/plot_window/slice_plot.py", line 363, in _run_temp_dependent
    slice_plotter_method(self.ws_name)
  File "/home/mdl27/src/mslice/mslice/presenters/slice_plotter_presenter.py", line 69, in show_dynamical_susceptibility
    plot_cached_slice(slice_cache, slice_cache.chi)
  File "/home/mdl27/src/mslice/mslice/models/slice/slice.py", line 47, in chi
    self._chi = compute_chi(self.scattering_function, self.sample_temp, self.energy_axis)
  File "/home/mdl27/src/mslice/mslice/models/slice/slice_functions.py", line 65, in compute_chi
    out = scattering_data * chi
  File "/home/mdl27/src/mslice/mslice/util/mantid/_workspace_ops.py", line 66, in op_wrapper
    return _binary_op(self, other, algorithm, result_info, inplace, reverse)
  File "/home/mdl27/src/mslice/mslice/util/mantid/_workspace_ops.py", line 47, in _binary_op
    inner_res = self._binary_op_array(_binary_operator_map[algorithm], other)
  File "/home/mdl27/src/mslice/mslice/workspace/workspace_mixin.py", line 54, in _binary_op_array
    new_signal = apply_with_corrected_shape(operator, signal, other, error)
  File "/home/mdl27/src/mslice/mslice/util/numpy_helper.py", line 21, in apply_with_corrected_shape
    raise exception
RuntimeError: List or array must have same number of elements as an axis of the workspace
```

Programatically you can check (after plotting the slice):

```
import mslice
e_axis = mslice.app.MAIN_WINDOW.slice_plotter_presenter.get_slice_cache('MAR18120_Ei39.53meV').energy_axis
print(mslice.models.alg_workspace_ops.get_number_of_steps(e_axis))
```

which returns `525`. 

Unfortunately I don't really know how to solve this problem...
