### ISSUE TITLE
Incorrect cache used for intensity calculation when switching files

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mslice#361]
The non-default intensity options don't lookup the log value correctly for files from different instruments.

== Steps to reproduce ==

* Load the test `MAR21335_Ei60.00meV.nxs` dataset
* display a slice
* select Intensity->Chi'' and choose `t_head` as the log
* close the plot
* load the test `SEQ_70280_autoreduced.nxspe` dataset
* calculate a projection
* display a slice -> error displayed: `Unknown property search object t_head`

I think this also raises a question as to what should happen when you close a plot. Currently if I display a slice, change the intensity, close the plot then display it again I still the the intensity set to what the closed plot was displaying. It would seem more intuitive to me that a new plot uses the defaults rather than what you last set or is this by design (I can't remember). @mducle Any thoughts?

**Comment by MatthewBowles** [comment]
I am currently working on this area in preparation for the plotting commands in the CLI (#358) so I can probably make the intensity / powder / recoil lines reset on close as part of that upcoming PR. 

I may add the fix for this bug depending on how long it ends up being - my initial reaction is that it's just a missing `try except` somewhere.

**Comment by martyngigg** [comment]
Instead of having to reset things can we not just delete the plot window object completely and create a new one? That would avoid having to remember to reset things...
