### ISSUE TITLE
List of files not updating on RHEL7

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mslice#431]
The list of NXSPE files is not updating on RHEL7. I am running Mslice through mantidplotnightly, release 3.13.20190214.2157.
To reproduce this bug:
 - create a folder with a couple of nxspe files
 - start Mslice, navigate to the folder
 - copy some extra nxspe files into the folder: the list of files does not update
 - you can try moving back and forth, still only the original files are visible

Works perfectly fine on Ubuntu 18.04. As soon as I add the file to the folder, it shows up in the list of files in the Data Loading tab

**Comment by mducle** [comment]
@AndreiSavici This is quite weird - I'm afraid I can't reproduce this... Do you see it in every folder or only in a particular folder? 

When I test it on my local RHEL machine (7.6) new files do appear in the dataloader (and if you remove a file it also disappears from the dataloader). 

I also tested on my home folder on `analysis.sns.gov` and a network folder which has public write access and it seems to work there as well. I couldn't actually test it with a network folder with user data because my SNS experiment was so long ago now that the data folder have been tape-archived and I don't have permission to write to that folder any more...

**Comment by AndreiSavici** [comment]
I've tested in my home folder on `analysis.sns.gov`

**Comment by mducle** [comment]
This is a possible work-around which reinitialises the `QFileSystemModel` to hopefully capture any changes to the folder...

**Comment by AndreiSavici** [comment]
Seems to be working
