### ISSUE TITLE
Adding Bragg peaks when interactive cut window still open causes error

### ISSUE THREAD

**Issue by SilkeSchomann** [mantidproject/mslice#641]
**Describe the bug**
When an interactive cut window is open, if you try and add a Bragg peak to the slice plot it will not be added, but will still be marked as there. If you then close the interactive cut and try to remove the Bragg peak you get an error.

**To Reproduce**
1. In the Workspace Manager tab of the MSlice interface select the workspace MAR21335_Ei60meV
2. Navigate to the ``Slice`` tab of the ``Workspace Manager`` tab
3. Click ``Display`` in the ``Slice`` tab without changing the default values
4. On the slice plot, select ``Interactive Cuts``
5. Use the cursor to select a rectangular region in the slice plot. A second window with a cut plot should open.
6. Navigate to the ``Information`` menu on the slice plot
7. Select ``Aluminium`` from the submenu for Bragg peaks
8. The Bragg peaks are not displayed but are marked as selected in the menu
9. Close the window with the cut
10. An error message appears (ValueError)

**Expected behavior**
In step 8. the Bragg peaks should get displayed and after step 9. there should not be an error message.

**Mantid Version (please complete the following information):**
 - Mantid Version 6.2

**Comment by MialLewis** [comment]
Note: This bug is caused by the slice plot not being set as the 'active figure' in the above scenario. Any overplots applied via the slice plot interface therefore get applied to a different figure.

When the interactive cut toggle is selected, a cut made, and the cut plot generated, the function 'disable_make_current' is called in the 'Global Figure Manager'. This then prevents the 'active figure' from changing back to the slice plot when using the slice plot interface. 

This was introduced as a bug fix as part of this commit:
https://github.com/mantidproject/mslice/commit/dea0fa29d6a823f83e19869526a79e15a7dbdc78#diff-df5c5ecaa6f2b4d1be1af12e326352ba3ebd768d1c49b8c4c30afc0a303c83a2

For this issue:
https://github.com/mantidproject/mslice/issues/403

It does not seem like a good solution to disable the activation of figures without locking the user to a specific figure.

Upon rolling back the fix and testing the prior state, it is clear that interactive cut, keep and make current work inconsistently.

Suggest a rework of the way interactive cut deals with active figures.
