### ISSUE TITLE
Zoom stuck after slice intensity change

### ISSUE THREAD

**Issue by MialLewis** [mantidproject/mslice#841]
**Describe the bug**
If you zoom in on a slice then change intensity, you can not use the tool bar to zoom back out again, having to adjust the axis limits manually.

**To Reproduce**
1. Plot Slice
2. Zoom in via `+`
3. Change intensity via `Intensity` drop down.
4. Attempt to zoom out via `-`

**Expected behavior**
Should be able to zoom back out to the original view. The

**MSlice Version (please complete the following information):**
 - MSlice Version [e.g. 2.3.0, from `import mslice; print(mslice.__version__)`]

**Additional context**

**Comment by robertapplin** [comment]
The zoom gets stuck because the history of the toolbar gets cleared on this line

https://github.com/mantidproject/mslice/blob/99f417f26ef9b68bd226676dfffaab3962903ca7/src/mslice/views/slice_plotter.py#L24

when replotting with a different intensity selected. I don't think there is much we can do

One solution could be to unzoom the plot automatically when the intensity changes, setting it back to the original zoom, before doing the replot. What do you think @MialLewis ?

**Comment by MialLewis** [comment]
I think that's probably the best solution given what you outline
