### ISSUE TITLE
Remove `Group Selected` functionality

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mslice#98]
In #91 it was decided that operations on multiple selections would be a better approach and the grouping features should be removed.

The multiple selection feature is noted on the [first open release](https://github.com/mantidproject/mslice/projects/1#card-414845) card but is not yet an issue

**Comment by martyngigg** [comment]
@mducle The current workspace box also has a greyed out "Compose" button. Its purpose is unclear. 

Is it still required?

**Comment by mducle** [comment]
The "Compose" button is (was?) intended for basic workspace manipulations such as adding / subtracting / scaling. I think that since we now have a `cli` that it would make more sense for this functionality to be in the `cli` than directly in the GUI. I should check with some other people forst though if they'd be ok with this.
